### ISSUE TITLE
Hi, this doesnt work fine on chrome :(

### ISSUE THREAD

**Issue by MarcosGalaviz** [JaySunSyn/polymer-tinymce#3]
Hi, great component! congratulations and thanks, but it works fine in Edge but in chrome it doesnt show correctly ¿do you know why?

Thanks a lot again, I realy need this, but I am just starting with Polymer.

**Comment by JaySunSyn** [comment]
Thanks! Whats the error/problem?
Does the demo work in your browser? http://jaysunsyn.github.io/polymer-tinymce/components/polymer-tinymce/

**Comment by MarcosGalaviz** [comment]
Hi, I realy apreciate your coments, the demo that you mention works fine :( , I am using polymer CLI,  I just add this code

 `<polymer-tinymce id="editor"
                                     tinytoolbar="insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image"
                                     tinyplugins='["advlist autolink lists link image charmap print preview anchor","searchreplace visualblocks code fullscreen","insertdatetime media table contextmenu paste"]'></polymer-tinymce>`

and in Edge works fine but in crome doesnt, as you can see in the images :(. 

In Edge:
![edge](https://cloud.githubusercontent.com/assets/14163318/19169694/2ab2b1c2-8bdb-11e6-8f2a-f08f4ee35b0d.gif)

But the same in chrome:
![chrome](https://cloud.githubusercontent.com/assets/14163318/19169688/276db2a0-8bdb-11e6-89d9-e41d4b596115.gif)

And I have another big problem that I don't understand :( when I install the component with the command:  `bower i polymer-tinymce -S` after that the command `polymer build` doesnt finish building,
![cmd](https://cloud.githubusercontent.com/assets/14163318/19169517/7fb4b838-8bda-11e6-8091-ce1a96b4fcdd.gif)
 I dont know why :(

**Comment by JaySunSyn** [comment]
Does your javascript console show errors?
MarcosGalaviz notifications@github.com schrieb am Do., 6. Okt. 2016 um
22:35:

**Comment by MarcosGalaviz** [comment]
No any error there jeje , is the devil :d

**Comment by JaySunSyn** [comment]
Do u load webcomponents.js conditionally in your index.html file? Force it
to load, does it solve the issue?
MarcosGalaviz notifications@github.com schrieb am Do., 6. Okt. 2016 um
23:01:

**Comment by MarcosGalaviz** [comment]
Thanks again for your answer, I hope not being disturbing you :(, I added this line, I guess with that line the webcomponents.js is loaded, but doesnt work :(

Could be something related toPolymer CLI? it works fine in firefox and Edge, but not in Chrome :(

![code](https://cloud.githubusercontent.com/assets/14163318/19193023/fbec38fc-8c6d-11e6-8a28-a08b9226a336.jpg)

**Comment by JaySunSyn** [comment]
I made some small changes but don't know if it will fix your issue.

Please run `bower update` and let me know if it works.

**Comment by MarcosGalaviz** [comment]
Thanks for your support, I executed bower update, but still the same problem :(, even I install a new proyect with: `polymer init`  just to test and I only add your component but I have the same Issue :(.

It shuld be something with polymer cli I think :(.

**Comment by JaySunSyn** [comment]
try now, I've only updated the bower and it seems to work with cli. Does it?

**Comment by JaySunSyn** [comment]
Feel free to re-open this issue if you still have problems.

**Comment by MarcosGalaviz** [comment]
Hi thanks a lot, I realy don't understand but still not working in chrome :( I did this:

Installed with: polymer init : app-drawer-template

just install the component and try to use it, in edge works but not in chrome :(

**Comment by jpicus** [comment]
Same problem here: works fine on IE, but not on chrome. No error...nothing.

**Comment by jpicus** [comment]
Problem solved: you need to swith from shadow to shady
=> https://www.polymer-project.org/1.0/docs/devguide/settings

**Comment by JaySunSyn** [comment]
@jpicus thanks, added a hint Readme.md
