### ISSUE TITLE
Remove menubar

### ISSUE THREAD

**Issue by winniequartey** [JaySunSyn/polymer-tinymce#4]
Hi, great element.
 I realize that there's no option to remove the menubar. I'm I wrong?
I would like to remove the menu bar. Any help.

**Comment by JaySunSyn** [comment]
@winniequartey check it out 1.0.3

http://jaysunsyn.github.io/polymer-tinymce/components/polymer-tinymce/

**Comment by winniequartey** [comment]
Great Thanks!!

**Comment by JaySunSyn** [comment]
glad it worked! Pls star the repo if you like this element ;)
