### ISSUE TITLE
Dynamic name attribute on textarea

### ISSUE THREAD

**Issue by jessetinell** [JaySunSyn/polymer-tinymce#5]
Would be great if the `name` attribute on the `textarea` wasn't hard coded to "content". 
For example: 
`<textarea id="[[textareaId]]" name="[[name]]" style="width: 100%" class="te">`

It would be easier to receive the content for a specific field on the server side.
Do you agree? :)

/Jesse

**Comment by JaySunSyn** [comment]
@jessetinell  not sure if this works for you, checkout the master branch, if ok I'll release a new version. I'm a bit drunk so let me know...

**Comment by JaySunSyn** [comment]
@jessetinell not sure if you could reach the textfield within a form even with a dynamic name attribute. Did you try it?
