### ISSUE TITLE
getContent doesn't take account of parameters 

### ISSUE THREAD

**Issue by jpicus** [JaySunSyn/polymer-tinymce#7]
We tried to make a "this.$.editor.getContent({format : 'text'});", a this.$.editor.getContent({format : 'raw'}); (and so on)

It seems that the "format" parameter is not working.

**Comment by JaySunSyn** [comment]
@jpicus Thanks, added it now. Try new version by running `bower update` https://github.com/JaySunSyn/polymer-tinymce/releases/tag/1.0.5

**Comment by JaySunSyn** [comment]
@jpicus Fell free to reopen if you still have issues.
