### ISSUE TITLE
paste as text only

### ISSUE THREAD

**Issue by kellykamay** [JaySunSyn/polymer-tinymce#8]
Hello is there a way that i could make paste as text as a default?

thanks

**Comment by JaySunSyn** [comment]
You can listen to e.g. `on-tiny-init="setInitialTextMethod"` an then set the initial text with `setContent()`. Please let me know if this works for you.

**Comment by JaySunSyn** [comment]
@kellykamay I think I misunderstood. What do you mean with "make paste as text as a default"?

**Comment by kellykamay** [comment]
Well for example  I will copy a content from other article and paste it into my editor; for sure the styling of that content will be included. 

How can i remove the styling and convert the content into plain text before it will be pasted on the editor? By not using the Edit>Paste as Text in menu bar?

**Comment by kellykamay** [comment]
Hello I found a solution to my problem, I just added these line of codes inside polymer-tinymce.html under tinymce.init() method
>   tinymce.init({
>      ...
>     paste_auto_cleanup_on_paste : true,
>     paste_remove_styles: true,
>     paste_remove_styles_if_webkit: true,
>     paste_strip_class_attributes: "all",
>     paste_as_text:true
>     ...
>    });

Thanks

**Comment by JaySunSyn** [comment]
Ah ok, you can now set the `initOptions` property.

```
<polymer-tinymce init-options='{"paste_auto_cleanup_on_paste" : true, "paste_remove_styles": true}'></polymer-tinymce>
```

Please run `bower update` and let me know if it works.

Thanks.

**Comment by kellykamay** [comment]
Cool...it's working now...Thanks!

**Comment by JaySunSyn** [comment]
Great!
